container:
  dockerfile: ci/Dockerfile

cargo_cache:
  folder: $CARGO_HOME/registry
  fingerprint_script: cat Cargo.lock

before_cache_script: rm -rf $CARGO_HOME/registry/index


build_task:
  build_script:
    - cargo build --workspace --verbose
    - cargo build --examples --verbose

task:
  matrix:
    - name: test
      test_script: cargo test --workspace --verbose
    - name: test (release)
      test_script: cargo test --release --workspace --verbose
    - name: format
      fmt_script: cargo fmt --all -- --check
    - name: clippy
      clippy_script: cargo clippy --workspace --all-targets --all-features -- -D warnings
  depends_on:
    - build
    

