language: rust
rust:
  - beta

cache: cargo

stages:
  - build
  - clippy
  - test
  - format

jobs:
  include:
    - stage: build
      script: cargo build --verbose --all

    - stage: clippy
      before_script: rustup component add clippy
      script: cargo clippy --all

    - stage: test
      script: cargo test --verbose --all

    - stage: format
      before_script: rustup component add rustfmt
      script: cargo fmt --all -- --check